services:
  movieapi:
    build:
      context: ../Movies-api-challenge.1.0.2/ApiApplication
      dockerfile: Dockerfile 
    ports:
      - "8081:80"
      - "8082:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/aspnetapp.pfx
    depends_on:
      - cache
      - externalmovieapi
  externalmovieapi:
    image: lodgify/movies-api:3
    ports:
      - "7172:80"
      - "7443:443"
    environment:      
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/aspnetapp.pfx
  cache:
    image: "redis"
    restart: unless-stopped
    ports:
      - "6379:6379"
